[project]
name = "sharedcache"
version = "0.0.1"
description = "A cache for slow data fetching operations"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "filelock>=3.16.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
